---
- name: check if the encryption config already exists
  stat:
    path: "/root/encryption-config.yaml"
  become: true
  run_once: true
  register: encryption_config_stat

- name: generate the encryption key
  local_action: "shell head -c 32 /dev/urandom | base64"
  run_once: true
  register: encryption_key_output
  when: encryption_config_stat.stat.exists == False

- name: store the encryption key variable
  set_fact:
    encryption_key: "{{ encryption_key_output.stdout }}"
  run_once: true
  when: encryption_config_stat.stat.exists == False

- name: template the encryption config to the masters
  template:
    src: "{{ templates_path }}/encryption-config.yml.j2"
    dest: "/root/encryption-config.yaml"
  become: true
  when: encryption_config_stat.stat.exists == False
