---
- import_tasks: facts.yml

- import_tasks: dirs.yml

- import_tasks: cfssl.yml

- import_tasks: pki.yml

- import_tasks: encryption.yml

- import_tasks: docker.yml

- import_tasks: k8s-base.yml

- import_tasks: consul.yml
  when: consul_enable

- import_tasks: etcd.yml

- import_tasks: k8s-control-plane.yml

- import_tasks: flannel.yml

- import_tasks: kube-dns.yml
